# Generated by Django 6.0.3 on 2026-03-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_consultation_id_alter_diseaseinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='symptomsname',
            field=models.TextField(),
        ),
    ]
